### ISSUE TITLE
Incorrect language

### ISSUE THREAD

**Issue by lindemann09** [ShareStats/itembank#4]
This item is not Dutch, but is in the "dutch folder". Where is vufgb-bargraph-001-en.Rmd?

https://github.com/ShareStats/itembank/blob/3492c3d93adcbe0fc6c844c0adda2328985d9e68/Descriptive-statistics/vufgb-bargraph-001-nl/vufgb-bargraph-001-en.Rmd#L3

**Comment by ShKlinkenberg** [comment]
I see you changed the file name. Only the folder name also needs to be en instead of nl

From: Oliver Lindemann ***@***.***>
Date: Tuesday, 8 November 2022 at 11:58
To: ShareStats/itembank ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ShareStats/itembank] Incorrect language (Issue #4)

This item is not Dutch!

https://github.com/ShareStats/itembank/blob/3492c3d93adcbe0fc6c844c0adda2328985d9e68/Descriptive-statistics/vufgb-bargraph-001-nl/vufgb-bargraph-001-en.Rmd#L3<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FShareStats%2Fitembank%2Fblob%2F3492c3d93adcbe0fc6c844c0adda2328985d9e68%2FDescriptive-statistics%2Fvufgb-bargraph-001-nl%2Fvufgb-bargraph-001-en.Rmd%23L3&data=05%7C01%7Cs.klinkenberg%40uva.nl%7C029b473c85064b68c05208dac1782b33%7Ca0f1cacd618c4403b94576fb3d6874e5%7C0%7C0%7C638035019122765401%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=OV31nOPjV5cQtW81n0sMXmDmgxW2wCBxOK1%2BEdgADTs%3D&reserved=0>
